### ISSUE TITLE
bindash also use this library

### ISSUE THREAD

**Issue by jianshu93** [lemire/rollinghashcpp#14]
Hello @lemire,

Bindash is an ultra fast genome compare tools and it relies on this rolling hash library (https://github.com/zhaoxiaofei/bindash). It would be nice if you can also mentioned it somewhere in readme, showing the wide application of the library in bioinformatics.

Thanks,

Jianshu

**Comment by lemire** [comment]
Or you interested in adding a pull request ?

**Comment by jianshu93** [comment]
I have pulled a request.
Jianshu

**Comment by lemire** [comment]
Closed by PR.
