### ISSUE TITLE
64-bit hashes

### ISSUE THREAD

**Issue by ilyaminkin** [lemire/rollinghashcpp#4]
Hi,

Is it possible to obtain somehow 64 bit hash values? I need hashes for a Bloom filter, so 2^32 bits are not enough: my application will require to use a filter of size much larger than 2^32 entries.

**Comment by lemire** [comment]
Yes, please see 

https://github.com/lemire/rollinghashcpp/blob/master/example64bits.cpp

Thanks for raising the issue. I am closing this, reopen if you disagree.

**Comment by ilyaminkin** [comment]
Thank you! Should I specify "mywordsize" to be 64 as well?

**Comment by lemire** [comment]
That is correct.

I have added the 64-bit versions to the unit tests.
