### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by cup** [lemire/rollinghashcpp#9]
some to compare:

- http://github.com/cmuratori/meow_hash
- http://github.com/google/highwayhash
- http://github.com/jandrewrogers/MetroHash
- http://github.com/leo-yuriev/t1ha

**Comment by cup** [comment]
https://github.com/cmuratori/meow_hash/issues/1
https://github.com/jandrewrogers/MetroHash/issues/7
https://github.com/lemire/rollinghashcpp/issues/9

**Comment by lemire** [comment]
Pull requests are invited. I am certainly interested in benchmarks regarding various universal rolling hash functions.

If you want to help out, it would be great. As is it is, I am not going to have time to follow-up.

Reopen if you are willing to provide the implementations.
